// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlQLSen5BS8WI-nbPsROdyNJtaAuCxziM',
    appId: '1:489611987605:web:350b9944844218c319a99c',
    messagingSenderId: '489611987605',
    projectId: 'supplier-app-76956',
    authDomain: 'supplier-app-76956.firebaseapp.com',
    storageBucket: 'supplier-app-76956.firebasestorage.app',
    measurementId: 'G-C5EXLQH9E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Kc9BvCClA82o6JVeVGUIawp7SB1OoCc',
    appId: '1:489611987605:android:981fe9c877f056b819a99c',
    messagingSenderId: '489611987605',
    projectId: 'supplier-app-76956',
    storageBucket: 'supplier-app-76956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgX4hFNZTjKZkTxxSsjC5sqiEBap6hdb8',
    appId: '1:489611987605:ios:218d69241200a52919a99c',
    messagingSenderId: '489611987605',
    projectId: 'supplier-app-76956',
    storageBucket: 'supplier-app-76956.firebasestorage.app',
    iosBundleId: 'com.example.supplierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgX4hFNZTjKZkTxxSsjC5sqiEBap6hdb8',
    appId: '1:489611987605:ios:218d69241200a52919a99c',
    messagingSenderId: '489611987605',
    projectId: 'supplier-app-76956',
    storageBucket: 'supplier-app-76956.firebasestorage.app',
    iosBundleId: 'com.example.supplierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlQLSen5BS8WI-nbPsROdyNJtaAuCxziM',
    appId: '1:489611987605:web:1b5e2494d00013f119a99c',
    messagingSenderId: '489611987605',
    projectId: 'supplier-app-76956',
    authDomain: 'supplier-app-76956.firebaseapp.com',
    storageBucket: 'supplier-app-76956.firebasestorage.app',
    measurementId: 'G-4SDN9XBKKZ',
  );
}
